-- 0002_create_master_data_tables.sql

CREATE TABLE IF NOT EXISTS "Warehouses" (
    "Id" UUID PRIMARY KEY,
    "Code" VARCHAR(50) NOT NULL UNIQUE,
    "Name" VARCHAR(200) NOT NULL,
    "Address" TEXT NULL,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMPTZ NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "Zones" (
    "Id" UUID PRIMARY KEY,
    "WarehouseId" UUID NOT NULL REFERENCES "Warehouses"("Id") ON DELETE CASCADE,
    "Code" VARCHAR(50) NOT NULL,
    "Name" VARCHAR(200) NOT NULL,
    "ZoneType" VARCHAR(50) NOT NULL, -- e.g., Receiving, Storage, Staging, Shipping, Return
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMPTZ NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_zone_warehouse_code UNIQUE ("WarehouseId", "Code")
);

CREATE TABLE IF NOT EXISTS "Locations" (
    "Id" UUID PRIMARY KEY,
    "ZoneId" UUID NOT NULL REFERENCES "Zones"("Id") ON DELETE CASCADE,
    "Aisle" VARCHAR(20) NULL,
    "Bay" VARCHAR(20) NULL,
    "Level" VARCHAR(20) NULL,
    "Position" VARCHAR(20) NULL,
    "Barcode" VARCHAR(100) NULL UNIQUE,
    "MaxCapacity" DECIMAL(18,4) NULL,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMPTZ NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "Suppliers" (
    "Id" UUID PRIMARY KEY,
    "Code" VARCHAR(50) NOT NULL UNIQUE,
    "Name" VARCHAR(200) NOT NULL,
    "ContactPerson" VARCHAR(100) NULL,
    "Phone" VARCHAR(50) NULL,
    "Email" VARCHAR(100) NULL,
    "Address" TEXT NULL,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMPTZ NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "Customers" (
    "Id" UUID PRIMARY KEY,
    "Code" VARCHAR(50) NOT NULL UNIQUE,
    "Name" VARCHAR(200) NOT NULL,
    "ContactPerson" VARCHAR(100) NULL,
    "Phone" VARCHAR(50) NULL,
    "Email" VARCHAR(100) NULL,
    "Address" TEXT NULL,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMPTZ NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "Categories" (
    "Id" UUID PRIMARY KEY,
    "Code" VARCHAR(50) NOT NULL UNIQUE,
    "Name" VARCHAR(200) NOT NULL,
    "ParentCategoryId" UUID NULL REFERENCES "Categories"("Id") ON DELETE SET NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMPTZ NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "Units" (
    "Id" UUID PRIMARY KEY,
    "Code" VARCHAR(50) NOT NULL UNIQUE,
    "Name" VARCHAR(100) NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMPTZ NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "Products" (
    "Id" UUID PRIMARY KEY,
    "Code" VARCHAR(50) NOT NULL UNIQUE,
    "Name" VARCHAR(200) NOT NULL,
    "CategoryId" UUID NOT NULL REFERENCES "Categories"("Id") ON DELETE CASCADE,
    "UnitId" UUID NOT NULL REFERENCES "Units"("Id") ON DELETE RESTRICT,
    "SupplierId" UUID NULL REFERENCES "Suppliers"("Id") ON DELETE SET NULL,
    "Barcode" VARCHAR(100) NULL UNIQUE,
    "Description" TEXT NULL,
    "ImagePath" VARCHAR(500) NULL,
    "MinStock" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "MaxStock" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "ReorderPoint" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMPTZ NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE
);
